apache:
  image: httpd:2.4
  restart: always
  volumes:
    - ../:/var/www/coding-challenges
    - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    - /var/log:/var/log/apache2
  environment:
    - "APACHE_LOG_DIR=/var/log/apache2"
  ports:
    - "80:80"
  links:
    - php
php:
  image: php71-fpm:latest
  volumes:
    - ../:/var/www/coding-challenges
  links:
    - db
db:
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: develop
  ports:
    - "3306:3306"

adminer:
  image: adminer
  restart: always
  ports:
    - "8080:8080"