<?php

namespace App\Test\Controller;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

/**
 * Class ProductControllerTest
 * @package App\Test\Controller
 */
class ProductControllerTest extends TestCase
{
    private $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = new Client([
            'base_uri' => 'http://localhost',
            'http_errors' => false,
        ]);
    }

    public function testGetProducts()
    {
        $response = $this->client->get('/api/products', null);

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getBody(true), true);
        $this->assertArrayHasKey('id', reset($data));
    }

    public function testGetProduct()
    {
        $response = $this->client->get('/api/products/1', null);

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getBody(true), true);
        $this->assertArrayHasKey('id', $data);
    }

    public function testNotFoundProduct()
    {
        $response = $this->client->get('/api/products/9999', null);

        $this->assertEquals(404, $response->getStatusCode());
    }

    public function testCreateProduct()
    {
        $requestData = array(
            'name' => $name = 'product-' . uniqid(),
            'sku' => $sku = $name . '-sku',
            'quantity' => rand(1, 100),
            'category' => 'something',
        );

        $response = $this->client->post('/api/products', [
            'body' => json_encode($requestData)
        ]);

        $this->assertEquals(201, $response->getStatusCode());
        $data = json_decode($response->getBody(true), true);
        $this->assertArrayHasKey('name', $data);
        $this->assertEquals($data['name'], $name);
    }

    public function testPutProduct()
    {
        $requestData = array(
            'name' => $name = 'product-' . uniqid(),
            'sku' => $sku = $name . '-sku',
            'quantity' => rand(1, 100),
            'category' => 'something',
            'price' => rand(19, 99)
        );

        $response = $this->client->post('/api/products', [
            'body' => json_encode($requestData)
        ]);

        $data = json_decode($response->getBody(true), true);

        $updateData = [];

        // set new values to test update
        $updateData['quantity'] = $newQuantity = rand(101, 201);
        $updateData['name'] = 'new-' . $data['name'];
        $updateData['sku'] = 'new-' . $data['sku'];
        $updateData['category'] = 'new-category';
        $updateData['price'] = rand(100, 199);

        $response = $this->client->put(
            sprintf('/api/products/%s', $data['id']),
            ['body' => json_encode($updateData)]
        );

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getBody(true), true);
        $this->assertArrayHasKey('name', $data);
        $this->assertEquals($newQuantity, $updateData['quantity']);
    }
}